M1 support
SpaiR/imgui-java pull request #112
Opened 2022-02-11 23:37 UTC by Tom-Ski

- GHA is building arm64 slices
- Library loader detecting arm and 64bit to change choice of native lib
- gdx-jnigen is updated to 2.2.1
- Freetype is now being compiled and built in GHA into a fat library, and then used to link against when building the bindings.

2022-02-12 08:25 UTC, SpaiR commented
You need to configure an additional matrix build for arm. As it's done for all platforms. Like, no need to build a separate freetype for an amd build. As well as to configure an arm workaround when there is no need of it. Also, check job artefacts and you'll see that now there is only one dylib - the arm one. When it should be two of them.

And don't add to the PR compile arm binary, they are updated through the CI.

2022-02-12 08:25 UTC, SpaiR requested changes
You need to configure an additional matrix build for arm. As it's done for all platforms. Like, no need to build a separate freetype for an amd build. As well as to configure an arm workaround when there is no need of it. Also, check job artefacts and you'll see that now there is only one dylib - the arm one. When it should be two of them.

And don't add to the PR compiled arm binary, they are updated through the CI.

2022-02-12 11:59 UTC, Tom-Ski commented
Do you want to separate this at the generateLibs level? Atm type from the matrix is passed directly in, but another entry for arm will need that part adapting too.

Or should we just do some logic and feed in 'mac' still to generateLibs for that arm type?

Im not sure what you mean by not needing a separate build for arm, that is required. Do you mean no need to separate it when adding a new entry to the build matrix?

2022-02-22 15:33 UTC, SpaiR commented on .github/workflows/ci.yml
> +          sudo make install
You don't need it for amd64 builds.

2024-05-06 12:43 UTC, Displee commented
Can this be merged?

2024-08-04 21:40 UTC, SpaiR commented
Closing in favor of #223
I'll mention this PR in changelog as well. Thanks for the contrib! 🙏

2024-08-04 21:40 UTC, closed without merging