A good start for ImGuizmos
SpaiR/imgui-java pull request #41
Opened 2021-04-04 02:17 UTC by MrManiacc

I've implemented the base/required functions to get the ImGuizmos library running. I plan to add support for things like ImGradients etc.

2021-04-04 02:26 UTC, MrManiacc commented
Seems like all builds were fine other than the check style for some of the native functions. I don't think it's that big of a concern at the moment.

2021-04-04 06:00 UTC, SpaiR requested changes
Great stuff! Thanks for your contribution, I very apprecciate your input.

Problems I see from the first look:
- Cleanups. `imgui-binding/tmp` should not exist. As well as shadow plugin etc. If you need to test out your code - use example module. It could be started with locally built libraries.
- Speaking about example: you need to provide one. As it's done for node-graphs bindings. It should demonstrotate how to use binding in Java ecosystem. Number of features you can show there depends on you, but it's required to exist for sure.
- It's `static native void`, not `native static void`. Please, keep code consistency.

Generally speaking, code is fine, but you need to pay more attention to details. And to revamp your code so it will follow style of other parts of the binding. I see that it's a draft implementation, so please mark your PR title in an appropriate way. Or make the PR itself as a draft (github has such functionality). Other than that, good job!

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/ImGuizmo.java
> +    }
Very strange code. Just pass `boolean`, don't use array.

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/ImGuizmo.java
> +    private native static void nBeginFrame(); /*
You don't need this method. Just make `public static native void beginFrame` and call native function there. So it should be like `call native method` not `call java method->which calls native method`. Java layer is needed to do custom logic, like extraction of internal data from types `ImFloat` etc. Other than that, do direct native calls.

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/ImGuizmo.java
> +
Wierd empty lines everywhere.

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/ImGuizmo.java
> +        ImVec2 size = ImGui.getWindowSize();
Both of those methods create new objects. In binding I avoid unnecessary allocations as much as possible. You should do something like that https://github.com/SpaiR/imgui-java/blob/0ed891f391f70e1ba4edf863a6f8d22ccca23c98/imgui-binding/src/main/java/imgui/internal/ImGuiDockNode.java#L651-L660

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/Operation.java
> +public enum Operation {
Do not use enums. See any class in `flag` package to get the idea.

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/ImGuizmo.java
> +    public static void recomposeMatrixFromComponents(float[] matrix, float[] translation, float[] rotation, float[] scale) {
Arguments order should be the same as for native method. Not something randomly generated. 😕

2021-04-04 06:00 UTC, SpaiR commented on imgui-binding/src/main/java/imgui/extension/imguizmo/ImGuizmo.java
> +        float[] matrices = new float[cubeMatrices.length * 16];
Speaking about unnecessary allocations, that is the case too.

2021-04-28 17:55 UTC, AAstroPhysiCS commented
Hi @MrManiacc,
I just wanted to ask if you're still working on this feature.
I am asking this because I plan to integrate this feature as well and in fact, I wanted to make a PR about it. Since, you've already done it, I did not want to make a another PR and just wait for you to finish.
If you stopped working on this feature or have limited time, I'll gladly take over your work and integrate this by myself.

Thanks for your contribution!

2021-05-08 08:48 UTC, MrManiacc commented
> Hi @MrManiacc,
> I just wanted to ask if you're still working on this feature.
> I am asking this because I plan to integrate this feature as well and in fact, I wanted to make a PR about it. Since, you've already done it, I did not want to make a another PR and just wait for you to finish.
> If you stopped working on this feature or have limited time, I can gladly take over your work and integrate this by myself.
> 
> Thanks for your contribution!

Hi, feel free to take over. I'm going to be very busy for the next couple of weeks.

2021-05-29 09:06 UTC, SpaiR commented
Implemented in #54

2021-05-29 09:06 UTC, closed without merging